### ISSUE TITLE
Invalid TXT Record Handling

### ISSUE THREAD

**Issue by Biztactix-Ryan** [alanedwardes/Ae.Dns#1]
I think it's to do with Long Text Records that get split into multiple records,
I can reliably reproduce with text record from _spf.mailgun.org
I've traced it back to the ReadString Function in DNSByteExtensions, It seems that it incorrectly parses the bytes as compressed and then reads through to the wrong Offset, Generating a
`new InvalidOperationException($"{resource.GetType().Name}.{nameof(IDnsResource.ReadBytes)} did not read to offset {expectedOffset} (read to {offset})");`

Unfortunately I'm not great at dealing with individual bits and don't know the DNS spec as well as you likely have come to.

So I'm not sure how to fix the issue, I can confirm if the Packet skips the isCompressed and heads down to the else case then reads it in as an ASCII, the output looks right
<img width="580" alt="image" src="https://user-images.githubusercontent.com/357433/193952086-53940500-0f69-4ed2-8605-f2db291f514b.png">

**Wireshark of the packet response**
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/357433/193952166-ff76b6fb-cc69-418e-8532-a0e44c4cfcad.png">

**Comment by alanedwardes** [comment]
Hello,

Thank you for the thorough report, this really reduced the time I needed to spend figuring things out.

I tweaked the string decompression algorithm to perform bounds checks which fixes this case. I'm still not happy with the logic in general however so if you have any more edge cases I can also add to the test suite let me know.

See https://github.com/alanedwardes/Ae.Dns/commit/4fe09094a1b5b56f6d4aa02b9e5dba7126f26407

Version `0.0.14` is now available on NuGet.

Alan

**Comment by Biztactix-Ryan** [comment]
Thanks for fixing that so quickly...  If I find any other edge cases, I'll shoot them over

I have also made a huge set of changes to improve performance of the Server Library, It's not at all clean and I can't quickly update a copy of yours, But if you're interested I can submit it.
It uses Memory<Byte> instead of reading the packet into a byte array and then passing it down through the logic,
By just passing the inbound packet's memory location down and using the slice function we don't have to assign new memory per packet.

<img width="614" alt="image" src="https://user-images.githubusercontent.com/357433/194179379-c2c46cc4-c40c-473d-ac1a-4738de1a0ccf.png">

**Comment by Biztactix-Ryan** [comment]
Actually, I did find an Issue with the Update... There's an Extra fullstop in the text record output where the split occurs

**Output from DNS Request**
`v=spf1 ip4:209.61.151.0/24 ip4:166.78.68.0/22 ip4:198.61.254.0/23 ip4:192.237.158.0/23 ip4:23.253.182.0/23 ip4:104.130.96.0/28 ip4:146.20.113.0/24 ip4:146.20.191.0/24 ip4:159.135.224.0/20 ip4:69.72.32.0/20. ip4:104.130.122.0/23 ip4:146.20.112.0/26 ip4:161.38.192.0/20 ip4:143.55.224.0/21 ip4:143.55.232.0/22 ip4:159.112.240.0/20 ~all`

**Actual Record**
`v=spf1 ip4:209.61.151.0/24 ip4:166.78.68.0/22 ip4:198.61.254.0/23 ip4:192.237.158.0/23 ip4:23.253.182.0/23 ip4:104.130.96.0/28 ip4:146.20.113.0/24 ip4:146.20.191.0/24 ip4:159.135.224.0/20 ip4:69.72.32.0/20 ip4:104.130.122.0/23 ip4:146.20.112.0/26 ip4:161.38.192.0/20 ip4:143.55.224.0/21 ip4:143.55.232.0/22 ip4:159.112.240.0/20 ~all`

Extra . after the 69.72.32.0/20

**Comment by alanedwardes** [comment]
> Actually, I did find an Issue with the Update... There's an Extra fullstop in the text record output where the split occurs

This was actually working as previously intended, since the DNS record you quoted consisted of two string entries. The behaviour was to concatenate entries with a period `.`, which works for CNAME records, but for plain TXT records it was a weird assumption.

I have now changed that and split out separate DNS string record types: `DnsDomainResource` and `DnsTextResource`. `DnsTextResource` has an `Entries` property, which provides the raw string values of the record (to concatenate or otherwise).

This is included in version `0.0.15` on NuGet.

> I have also made a huge set of changes to improve performance of the Server Library, It's not at all clean and I can't quickly update a copy of yours, But if you're interested I can submit it.
> It uses Memory instead of reading the packet into a byte array and then passing it down through the logic,
> By just passing the inbound packet's memory location down and using the slice function we don't have to assign new memory per packet.

I am definitely interested in performance optimisations, if there is a significant proven benefit (e.g. with benchmark data) and it doesn't hurt readability too much!

**Comment by Biztactix-Ryan** [comment]
I think Performance went from 40-60k Requests per Second on My Dev Box, to Over 80k Requests per Second, Obviously already way above the max that I'd need for my use case, I started running into timeouts of requests up around there, I think it might be due to socket exhaustion, Comparing it to an off the shelf Linux DNS server they were around the 120k Rps i believe, So certainly a good outcome, especially for a JIT language, With some code changes may even be able to get full AOT compilation happening, but I already spent a day getting it this far.

-edit- Oh, of course that's for Static response that is in memory of the server, No forwarding queries here, that would drop it to 1/10th of that number.

**Comment by alanedwardes** [comment]
I would be interested in how you're actually performing these benchmarks, is it with https://github.com/dotnet/BenchmarkDotNet ?

I will close this issue, since the original problem is fixed. Maybe another issue will be better to discuss performance of specific bits of code (I have done zero work on perf since that's not my use case, but like I said, open to improving it).
