### ISSUE TITLE
More typos

### ISSUE THREAD

**Issue by SamLowryMOI** [alanedwardes/Ae.Dns#16]
I hope you don't hate me.
Search for ```RecusionDesired```, ```recrusion``` and ```recusion``` in ```*.cs``` files.

**Comment by alanedwardes** [comment]
🙈 

Please feel free to raise a PR around this

**Comment by SamLowryMOI** [comment]
I think this has the same priority for me as for you...

**Comment by alanedwardes** [comment]
I'm preparing this for V1 of the lib: https://github.com/alanedwardes/Ae.Dns/pull/18
