### ISSUE TITLE
GetReverseLookupHostForIpAddress is incorrect for some ipv6 addresses

### ISSUE THREAD

**Issue by SamLowryMOI** [alanedwardes/Ae.Dns#17]
Try ```CreateReverseQuery``` with an ipv6 address like ```2a02:2e0:3fe:1001:302::```.
You get ```2.0.3.1.0.0.1.e.f.3.0.e.2.2.0.a.2.ip6.arpa``` 
instead of ```0.0.0.0.0.0.0.0.0.0.0.0.2.0.3.0.1.0.0.1.e.f.3.0.0.e.2.0.2.0.a.2.ip6.arpa```.

**Comment by alanedwardes** [comment]
Interesting! Do you happen to know how to refer to the latter format? In other words, the technical name for that layout of an IPv6 addess?

**Comment by alanedwardes** [comment]
(or rather, the technical name before it is reversed as required for the reverse lookup query)

**Comment by SamLowryMOI** [comment]
> technical name

If there is a name, I have never heard it. 
But you have to use the 'uncompressed' form for reverse lookups.

**Comment by alanedwardes** [comment]
I see - I think that might be the technical name :-)

I will take a look at fixing this when I have some time - here's where the bug is: https://github.com/alanedwardes/Ae.Dns/blob/eb3e202b09b13f11abee46ed69c7201e00e807d3/src/Ae.Dns.Protocol/DnsQueryFactory.cs#L97

`ipAddress.ToString()` is doing the wrong thing by default (I'd assume there's a missing format specifier, etc)

**Comment by SamLowryMOI** [comment]
My workaround (really no one-liner):

```
var text = "ip6.arpa";
byte[] addressBytes = ipAddress.GetAddressBytes();
foreach (byte num in addressBytes)
{
    byte b = (byte)(num & 0xFu);
    byte b2 = (byte)((num & 0xF0) >> 4);
    text = $"{b:X}.{b2:X}.{text}";
}
return text;
```

**Comment by SamLowryMOI** [comment]
I've got a one-liner:

```
return string.Join(".", BitConverter.ToString(ipAddress.GetAddressBytes()).Replace("-", string.Empty).ToCharArray().Reverse()) + ".ip6.arpa";
```

**Comment by alanedwardes** [comment]
Thanks, I'm preparing this for V1 of the lib: https://github.com/alanedwardes/Ae.Dns/pull/18
