### ISSUE TITLE
Ae.Dns.Tests needs now unsupported .Net Core 2.1?

### ISSUE THREAD

**Issue by SamLowryMOI** [alanedwardes/Ae.Dns#9]
My Visual Studio wanted to install the .Net Core 2.1 because the file `Ae.Dns.Tests.csproj` says:

`
		<TargetFrameworks>net6.0;netcoreapp3.1;netcoreapp2.1</TargetFrameworks>
`

Is this intentional?

**Comment by alanedwardes** [comment]
Yes, otherwise there is no way to validate that the netstandard2.0 code is working as expected (and it wasn’t after my initial port, these tests identified bugs which needed fixing).
